/*
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2001
 */
public class InlineResponse2001Test {
    private final InlineResponse2001 model = new InlineResponse2001();

    /**
     * Model tests for InlineResponse2001
     */
    @Test
    public void testInlineResponse2001() {
        // TODO: test InlineResponse2001
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'confluxaddress'
     */
    @Test
    public void confluxaddressTest() {
        // TODO: test confluxaddress
    }

    /**
     * Test the property 'ethaddress'
     */
    @Test
    public void ethaddressTest() {
        // TODO: test ethaddress
    }

    /**
     * Test the property 'paymentpassword'
     */
    @Test
    public void paymentpasswordTest() {
        // TODO: test paymentpassword
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
