/*
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject1
 */
public class InlineObject1Test {
    private final InlineObject1 model = new InlineObject1();

    /**
     * Model tests for InlineObject1
     */
    @Test
    public void testInlineObject1() {
        // TODO: test InlineObject1
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'randomtoken'
     */
    @Test
    public void randomtokenTest() {
        // TODO: test randomtoken
    }

    /**
     * Test the property 'paymentpassword'
     */
    @Test
    public void paymentpasswordTest() {
        // TODO: test paymentpassword
    }

    /**
     * Test the property 'openid'
     */
    @Test
    public void openidTest() {
        // TODO: test openid
    }

}
