/*
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-01T20:35:15.858+08:00[Asia/Shanghai]")
public class InlineObject1 {
  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  private String account;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private Integer time;

  public static final String SERIALIZED_NAME_RANDOMTOKEN = "randomtoken";
  @SerializedName(SERIALIZED_NAME_RANDOMTOKEN)
  private String randomtoken;

  public static final String SERIALIZED_NAME_PAYMENTPASSWORD = "paymentpassword";
  @SerializedName(SERIALIZED_NAME_PAYMENTPASSWORD)
  private String paymentpassword;

  public static final String SERIALIZED_NAME_OPENID = "openid";
  @SerializedName(SERIALIZED_NAME_OPENID)
  private String openid;


  public InlineObject1 phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public InlineObject1 account(String account) {
    
    this.account = account;
    return this;
  }

   /**
   * 通过接入jugugu申请
   * @return account
  **/
  @ApiModelProperty(required = true, value = "通过接入jugugu申请")

  public String getAccount() {
    return account;
  }


  public void setAccount(String account) {
    this.account = account;
  }


  public InlineObject1 secret(String secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * 通过接入jugugu申请
   * @return secret
  **/
  @ApiModelProperty(required = true, value = "通过接入jugugu申请")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public InlineObject1 time(Integer time) {
    
    this.time = time;
    return this;
  }

   /**
   * int64类型
   * @return time
  **/
  @ApiModelProperty(required = true, value = "int64类型")

  public Integer getTime() {
    return time;
  }


  public void setTime(Integer time) {
    this.time = time;
  }


  public InlineObject1 randomtoken(String randomtoken) {
    
    this.randomtoken = randomtoken;
    return this;
  }

   /**
   * 可以由sha256函数随机产生，避免2分钟内重复，可用时间+其他唯一参数作为种子，防止重放攻击
   * @return randomtoken
  **/
  @ApiModelProperty(required = true, value = "可以由sha256函数随机产生，避免2分钟内重复，可用时间+其他唯一参数作为种子，防止重放攻击")

  public String getRandomtoken() {
    return randomtoken;
  }


  public void setRandomtoken(String randomtoken) {
    this.randomtoken = randomtoken;
  }


  public InlineObject1 paymentpassword(String paymentpassword) {
    
    this.paymentpassword = paymentpassword;
    return this;
  }

   /**
   * 可以自由设置也可以传“”空字符串，系统随机生成，建议让系统随机生成
   * @return paymentpassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "可以自由设置也可以传“”空字符串，系统随机生成，建议让系统随机生成")

  public String getPaymentpassword() {
    return paymentpassword;
  }


  public void setPaymentpassword(String paymentpassword) {
    this.paymentpassword = paymentpassword;
  }


  public InlineObject1 openid(String openid) {
    
    this.openid = openid;
    return this;
  }

   /**
   * 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
   * @return openid
  **/
  @ApiModelProperty(required = true, value = "项目方账户系统的唯一识别码，用于绑定登录jugugu系统")

  public String getOpenid() {
    return openid;
  }


  public void setOpenid(String openid) {
    this.openid = openid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return Objects.equals(this.phone, inlineObject1.phone) &&
        Objects.equals(this.account, inlineObject1.account) &&
        Objects.equals(this.secret, inlineObject1.secret) &&
        Objects.equals(this.time, inlineObject1.time) &&
        Objects.equals(this.randomtoken, inlineObject1.randomtoken) &&
        Objects.equals(this.paymentpassword, inlineObject1.paymentpassword) &&
        Objects.equals(this.openid, inlineObject1.openid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, account, secret, time, randomtoken, paymentpassword, openid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    randomtoken: ").append(toIndentedString(randomtoken)).append("\n");
    sb.append("    paymentpassword: ").append(toIndentedString(paymentpassword)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

