/*
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-01T20:35:15.858+08:00[Asia/Shanghai]")
public class InlineObject {
  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  private String account;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private Integer time;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_OPENID = "openid";
  @SerializedName(SERIALIZED_NAME_OPENID)
  private String openid;

  public static final String SERIALIZED_NAME_CONTRACT = "contract";
  @SerializedName(SERIALIZED_NAME_CONTRACT)
  private String contract;

  public static final String SERIALIZED_NAME_NFTID = "nftid";
  @SerializedName(SERIALIZED_NAME_NFTID)
  private String nftid;

  public static final String SERIALIZED_NAME_CODESTR = "codestr";
  @SerializedName(SERIALIZED_NAME_CODESTR)
  private String codestr;

  public static final String SERIALIZED_NAME_CHAINTYPE = "chaintype";
  @SerializedName(SERIALIZED_NAME_CHAINTYPE)
  private String chaintype;


  public InlineObject phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public InlineObject address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public InlineObject account(String account) {
    
    this.account = account;
    return this;
  }

   /**
   * 通过接入jugugu申请
   * @return account
  **/
  @ApiModelProperty(required = true, value = "通过接入jugugu申请")

  public String getAccount() {
    return account;
  }


  public void setAccount(String account) {
    this.account = account;
  }


  public InlineObject secret(String secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * 通过接入jugugu申请
   * @return secret
  **/
  @ApiModelProperty(required = true, value = "通过接入jugugu申请")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public InlineObject time(Integer time) {
    
    this.time = time;
    return this;
  }

   /**
   * int64类型
   * @return time
  **/
  @ApiModelProperty(required = true, value = "int64类型")

  public Integer getTime() {
    return time;
  }


  public void setTime(Integer time) {
    this.time = time;
  }


  public InlineObject token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * 通过登录获得，首次注册时也会获得
   * @return token
  **/
  @ApiModelProperty(required = true, value = "通过登录获得，首次注册时也会获得")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public InlineObject openid(String openid) {
    
    this.openid = openid;
    return this;
  }

   /**
   * 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
   * @return openid
  **/
  @ApiModelProperty(required = true, value = "项目方账户系统的唯一识别码，用于绑定登录jugugu系统")

  public String getOpenid() {
    return openid;
  }


  public void setOpenid(String openid) {
    this.openid = openid;
  }


  public InlineObject contract(String contract) {
    
    this.contract = contract;
    return this;
  }

   /**
   * 正式网合约：cfx:acb2027ht5t916d323zjfw9knrdj42fm8ay9n7e3x0  测试网合约：cfxtest:acbk50byfusjyh7494rm8yd8xhnkdh9jyetgadzem4
   * @return contract
  **/
  @ApiModelProperty(required = true, value = "正式网合约：cfx:acb2027ht5t916d323zjfw9knrdj42fm8ay9n7e3x0  测试网合约：cfxtest:acbk50byfusjyh7494rm8yd8xhnkdh9jyetgadzem4")

  public String getContract() {
    return contract;
  }


  public void setContract(String contract) {
    this.contract = contract;
  }


  public InlineObject nftid(String nftid) {
    
    this.nftid = nftid;
    return this;
  }

   /**
   * Get nftid
   * @return nftid
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNftid() {
    return nftid;
  }


  public void setNftid(String nftid) {
    this.nftid = nftid;
  }


  public InlineObject codestr(String codestr) {
    
    this.codestr = codestr;
    return this;
  }

   /**
   * Get codestr
   * @return codestr
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCodestr() {
    return codestr;
  }


  public void setCodestr(String codestr) {
    this.codestr = codestr;
  }


  public InlineObject chaintype(String chaintype) {
    
    this.chaintype = chaintype;
    return this;
  }

   /**
   * 这里填cfx即可
   * @return chaintype
  **/
  @ApiModelProperty(required = true, value = "这里填cfx即可")

  public String getChaintype() {
    return chaintype;
  }


  public void setChaintype(String chaintype) {
    this.chaintype = chaintype;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.phone, inlineObject.phone) &&
        Objects.equals(this.address, inlineObject.address) &&
        Objects.equals(this.account, inlineObject.account) &&
        Objects.equals(this.secret, inlineObject.secret) &&
        Objects.equals(this.time, inlineObject.time) &&
        Objects.equals(this.token, inlineObject.token) &&
        Objects.equals(this.openid, inlineObject.openid) &&
        Objects.equals(this.contract, inlineObject.contract) &&
        Objects.equals(this.nftid, inlineObject.nftid) &&
        Objects.equals(this.codestr, inlineObject.codestr) &&
        Objects.equals(this.chaintype, inlineObject.chaintype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, address, account, secret, time, token, openid, contract, nftid, codestr, chaintype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    nftid: ").append(toIndentedString(nftid)).append("\n");
    sb.append("    codestr: ").append(toIndentedString(codestr)).append("\n");
    sb.append("    chaintype: ").append(toIndentedString(chaintype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

