/*
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-01T20:35:15.858+08:00[Asia/Shanghai]")
public class InlineResponse2001 {
  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_CONFLUXADDRESS = "confluxaddress";
  @SerializedName(SERIALIZED_NAME_CONFLUXADDRESS)
  private String confluxaddress;

  public static final String SERIALIZED_NAME_ETHADDRESS = "ethaddress";
  @SerializedName(SERIALIZED_NAME_ETHADDRESS)
  private String ethaddress;

  public static final String SERIALIZED_NAME_PAYMENTPASSWORD = "paymentpassword";
  @SerializedName(SERIALIZED_NAME_PAYMENTPASSWORD)
  private String paymentpassword;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;


  public InlineResponse2001 phone(String phone) {
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public InlineResponse2001 confluxaddress(String confluxaddress) {
    
    this.confluxaddress = confluxaddress;
    return this;
  }

   /**
   * Get confluxaddress
   * @return confluxaddress
  **/
  @ApiModelProperty(required = true, value = "")

  public String getConfluxaddress() {
    return confluxaddress;
  }


  public void setConfluxaddress(String confluxaddress) {
    this.confluxaddress = confluxaddress;
  }


  public InlineResponse2001 ethaddress(String ethaddress) {
    
    this.ethaddress = ethaddress;
    return this;
  }

   /**
   * Get ethaddress
   * @return ethaddress
  **/
  @ApiModelProperty(required = true, value = "")

  public String getEthaddress() {
    return ethaddress;
  }


  public void setEthaddress(String ethaddress) {
    this.ethaddress = ethaddress;
  }


  public InlineResponse2001 paymentpassword(String paymentpassword) {
    
    this.paymentpassword = paymentpassword;
    return this;
  }

   /**
   * Get paymentpassword
   * @return paymentpassword
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPaymentpassword() {
    return paymentpassword;
  }


  public void setPaymentpassword(String paymentpassword) {
    this.paymentpassword = paymentpassword;
  }


  public InlineResponse2001 token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(required = true, value = "")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.phone, inlineResponse2001.phone) &&
        Objects.equals(this.confluxaddress, inlineResponse2001.confluxaddress) &&
        Objects.equals(this.ethaddress, inlineResponse2001.ethaddress) &&
        Objects.equals(this.paymentpassword, inlineResponse2001.paymentpassword) &&
        Objects.equals(this.token, inlineResponse2001.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, confluxaddress, ethaddress, paymentpassword, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    confluxaddress: ").append(toIndentedString(confluxaddress)).append("\n");
    sb.append("    ethaddress: ").append(toIndentedString(ethaddress)).append("\n");
    sb.append("    paymentpassword: ").append(toIndentedString(paymentpassword)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

